---
  cloud:
    username: "admin"
    projectname: "demo"
    password: "secret"
    auth_url: "http://172.16.166.13:5000/v2.0/tokens"
  vm_template:
    flavorRef: "42"
    networkRef: "69024462-61f6-4441-97b4-611b6a38290c"
    imageRef: "45ec29dc-b96a-4ebc-bd8c-b43c91781550"
    name_template: "vm_%d"
  run_number: 1
  backend:
    influx_host: "http://monit-ent.vm.mirantis.net:8086"
    database: "openstack"
  scenarios:
     simple:
       id: 1
       parallel: 2
       on_finish:
       - shutdown_telegraph
       on_sync_events:
       - start_telegraph
       steps:
       - build
       - create_floating_ip
       - wait_for_active
       - associate_floating_ip
       - start_ping
       - sync_execution
       - live_migrate
       - wait_for_active
       - stop_ping
       - delete
