---
  cloud:
    username: "admin"
    projectname: "admin"
    password: "secret"
    auth_url: "http://172.16.166.13:5000/v2.0/tokens"
  run_number: 1
  backend:
    influx_host: "http://monit-ent.vm.mirantis.net:8086"
    database: "huge_pages"
    callback_host: "172.18.66.80"
    callback_port: 9999
  periodic:
     - check_endpoints:
         period: 5.0
  scenarios:
     simple:
       load_config:
         vm_workers: 1
         malloc_mem_mb: 50
       vm_template:
         flavorRef: "2"
         networkRef: "d9fbd4d1-25a8-4e4d-9f19-30934293e52e"
         imageRef: "3036a5ba-8f04-404b-95d3-daf70ddb2c27"
#         key_name: "orchestra"
         name_template: "vm_%d"
         floating_ip_pool: "external-router"
#       pre_config:
#         nova_compress: false
#         nova_autoconverge: false
#         nova_concurrent_migrations: 1
#         nova_max_downtime: 500
       id: 1
       parallel: 5
       repeat: 1
       playbook_path: "/home/tdurakov/migration-monitor/ansible"
       hosts:
       - 172.16.166.14
       - 172.16.166.15
       on_finish:
       - shutdown_telegraph
#       on_sync_events:
#       - start_telegraph
#       - load_test
       steps:
       - build
       - create_floating_ip
       - wait_for:
           state: "ACTIVE"
       - associate_floating_ip
       - wait_for_floating_ip_associate
#       - start_ping:
#           frequency: 0.2
#           sync: true
       - wait_for_instance_become_available
#       - sync_execution
#       - sync_execution
#       - live_migrate
       - wait_for:
           state: "ACTIVE"
#       - stop_ping
#       - delete_instance
#       - wait_for_floating_ip_disassociate
#       - delete_floating_ip
