---
  cloud:
    username: "admin"
    projectname: "demo"
    password: "secret"
    auth_url: "http://172.16.166.13:5000/v2.0/tokens"
  run_number: 1
  backend:
    influx_host: "http://monit-ent.vm.mirantis.net:8086"
    database: "openstack"
  scenarios:
     simple:
       vm_template:
         flavorRef: "2"
         networkRef: "69024462-61f6-4441-97b4-611b6a38290c"
         imageRef: "431caa95-c0b1-47b2-82bd-5c5407efa909"
         key_name: "orchestra"
         name_template: "vm_%d"
       pre_config:
         nova_compress: false
         nova_autoconverge: false
         nova_concurrent_migrations: 1
       id: 1
       parallel: 1
       repeat: 10
       playbook_path: "/Users/tdurakov/migration-monitor/ansible"
       hosts:
       - 172.16.166.14
       - 172.16.166.15
       on_finish:
       - shutdown_telegraph
       on_sync_events:
       - start_telegraph
       steps:
       - build
       - create_floating_ip
       - wait_for_active
       - associate_floating_ip
       - start_ping
       - sync_execution
       - live_migrate
       - wait_for_active
       - stop_ping
       - delete
     simple_load:
       vm_template:
        flavorRef: "2"
        networkRef: "69024462-61f6-4441-97b4-611b6a38290c"
        imageRef: "431caa95-c0b1-47b2-82bd-5c5407efa909"
        key_name: "orchestra"
        name_template: "vm_%d"
      pre_config:
        nova_compress: false
        nova_autoconverge: false
        nova_concurrent_migrations: 1
      id: 2
      parallel: 1
      repeat: 10
      playbook_path: "/Users/tdurakov/migration-monitor/ansible"
      hosts:
      - 172.16.166.14
      - 172.16.166.15
      on_finish:
      - shutdown_telegraph
      on_sync_events:
      - start_telegraph
      - load_test
      steps:
      - build
      - create_floating_ip
      - wait_for_active
      - associate_floating_ip
      - start_ping
      - sync_execution
      - sync_execution
      - live_migrate
      - wait_for_active
      - stop_ping
      - delete
     simple-x:
       vm_template:
         flavorRef: "2"
         networkRef: "69024462-61f6-4441-97b4-611b6a38290c"
         imageRef: "431caa95-c0b1-47b2-82bd-5c5407efa909"
         key_name: "orchestra"
         name_template: "vm_%d"
       pre_config:
         nova_compress: true
         nova_autoconverge: false
         nova_concurrent_migrations: 1
       id: 3
       parallel: 1
       repeat: 10
       playbook_path: "/Users/tdurakov/migration-monitor/ansible"
       hosts:
       - 172.16.166.14
       - 172.16.166.15
       on_finish:
       - shutdown_telegraph
       on_sync_events:
       - start_telegraph
       steps:
       - build
       - create_floating_ip
       - wait_for_active
       - associate_floating_ip
       - start_ping
       - sync_execution
       - live_migrate
       - wait_for_active
       - stop_ping
       - delete
     simple_load-x:
       vm_template:
        flavorRef: "2"
        networkRef: "69024462-61f6-4441-97b4-611b6a38290c"
        imageRef: "431caa95-c0b1-47b2-82bd-5c5407efa909"
        key_name: "orchestra"
        name_template: "vm_%d"
      pre_config:
        nova_compress: true
        nova_autoconverge: false
        nova_concurrent_migrations: 1
      id: 4
      parallel: 1
      repeat: 10
      playbook_path: "/Users/tdurakov/migration-monitor/ansible"
      hosts:
      - 172.16.166.14
      - 172.16.166.15
      on_finish:
      - shutdown_telegraph
      on_sync_events:
      - start_telegraph
      - load_test
      steps:
      - build
      - create_floating_ip
      - wait_for_active
      - associate_floating_ip
      - start_ping
      - sync_execution
      - sync_execution
      - live_migrate
      - wait_for_active
      - stop_ping
      - delete
     simple-a:
        vm_template:
          flavorRef: "2"
          networkRef: "69024462-61f6-4441-97b4-611b6a38290c"
          imageRef: "431caa95-c0b1-47b2-82bd-5c5407efa909"
          key_name: "orchestra"
          name_template: "vm_%d"
        pre_config:
          nova_compress: false
          nova_autoconverge: true
          nova_concurrent_migrations: 1
        id: 5
        parallel: 1
        repeat: 10
        playbook_path: "/Users/tdurakov/migration-monitor/ansible"
        hosts:
        - 172.16.166.14
        - 172.16.166.15
        on_finish:
        - shutdown_telegraph
        on_sync_events:
        - start_telegraph
        steps:
        - build
        - create_floating_ip
        - wait_for_active
        - associate_floating_ip
        - start_ping
        - sync_execution
        - live_migrate
        - wait_for_active
        - stop_ping
        - delete
     simple_load-a:
        vm_template:
         flavorRef: "2"
         networkRef: "69024462-61f6-4441-97b4-611b6a38290c"
         imageRef: "431caa95-c0b1-47b2-82bd-5c5407efa909"
         key_name: "orchestra"
         name_template: "vm_%d"
       pre_config:
         nova_compress: false
         nova_autoconverge: true
         nova_concurrent_migrations: 1
       id: 6
       parallel: 1
       repeat: 10
       playbook_path: "/Users/tdurakov/migration-monitor/ansible"
       hosts:
       - 172.16.166.14
       - 172.16.166.15
       on_finish:
       - shutdown_telegraph
       on_sync_events:
       - start_telegraph
       - load_test
       steps:
       - build
       - create_floating_ip
       - wait_for_active
       - associate_floating_ip
       - start_ping
       - sync_execution
       - sync_execution
       - live_migrate
       - wait_for_active
       - stop_ping
       - delete
     simple-xa:
        vm_template:
          flavorRef: "2"
          networkRef: "69024462-61f6-4441-97b4-611b6a38290c"
          imageRef: "431caa95-c0b1-47b2-82bd-5c5407efa909"
          key_name: "orchestra"
          name_template: "vm_%d"
        pre_config:
          nova_compress: true
          nova_autoconverge: true
          nova_concurrent_migrations: 1
        id: 7
        parallel: 1
        repeat: 10
        playbook_path: "/Users/tdurakov/migration-monitor/ansible"
        hosts:
        - 172.16.166.14
        - 172.16.166.15
        on_finish:
        - shutdown_telegraph
        on_sync_events:
        - start_telegraph
        steps:
        - build
        - create_floating_ip
        - wait_for_active
        - associate_floating_ip
        - start_ping
        - sync_execution
        - live_migrate
        - wait_for_active
        - stop_ping
        - delete
     simple_load-xa:
        vm_template:
         flavorRef: "2"
         networkRef: "69024462-61f6-4441-97b4-611b6a38290c"
         imageRef: "431caa95-c0b1-47b2-82bd-5c5407efa909"
         key_name: "orchestra"
         name_template: "vm_%d"
       pre_config:
         nova_compress: true
         nova_autoconverge: true
         nova_concurrent_migrations: 1
       id: 6
       parallel: 1
       repeat: 10
       playbook_path: "/Users/tdurakov/migration-monitor/ansible"
       hosts:
       - 172.16.166.14
       - 172.16.166.15
       on_finish:
       - shutdown_telegraph
       on_sync_events:
       - start_telegraph
       - load_test
       steps:
       - build
       - create_floating_ip
       - wait_for_active
       - associate_floating_ip
       - start_ping
       - sync_execution
       - sync_execution
       - live_migrate
       - wait_for_active
       - stop_ping
       - delete