---
  cloud:
    username: "admin"
    projectname: "demo"
    password: "secret"
    auth_url: "http://172.16.166.13:5000/v2.0/tokens"
  run_number: 1
  backend:
    influx_host: "http://monit-ent.vm.mirantis.net:8086"
    database: "openstack"
  scenarios:
     simple:
       vm_template:
         flavorRef: "2"
         networkRef: "69024462-61f6-4441-97b4-611b6a38290c"
         imageRef: "431caa95-c0b1-47b2-82bd-5c5407efa909"
         key_name: "orchestra"
         name_template: "vm_%d"
       pre_config:
         nova_compress: false
         nova_autoconverge: false
         nova_concurrent_migrations: 1
       id: 1
       parallel: 1
       repeat: 10
       playbook_path: "/Users/tdurakov/migration-monitor/ansible"
       hosts:
       - 172.16.166.14
       - 172.16.166.15
       on_finish:
       - shutdown_telegraph
       on_sync_events:
       - start_telegraph
       steps:
       - build
       - create_floating_ip
       - wait_for:
           state: "ACTIVE"
       - associate_floating_ip
       - wait_for_floating_ip_associate
       - start_ping:
           frequency: 0.2
           sync: true
       - sync_execution
       - live_migrate
       - wait_for:
           state: "ACTIVE"
       - stop_ping
       - delete_instance
       - wait_for_floating_ip_disassociate
       - delete_floating_ip
