---
- hosts: hard
  remote_user: ubuntu
  become_method: sudo
  become: yes
  tasks:
  - name: clean libvirt NFS share for images
    command: rm -rf /var/lib/libvirt/images/config* /var/lib/libvirt/images/dom*
