---
- hosts: hard
  remote_user: ubuntu
  become_method: sudo
  become: yes
  tasks:
  - name: destroy domain
    command: virsh destroy {{ domain_name }}
    ignore_errors: yes
  - name: undefine domain
    command: virsh undefine {{ domain_name }}
    ignore_errors: yes
