---
- hosts: hard
  remote_user: ubuntu
  become_method: sudo
  become: yes
  tasks:
  - name: set qemu parameters
    command: virsh qemu-monitor-command --cmd "{{ item }}"
    with_items: "{{ qemu_monitor_commands }}"

  - name: migrate VM
    command: virsh migrate --live --p2p --verbose {{ virsh_migrate_commandline_args }} {{ domain_name }} {{ destination_uri }}
    # async: 300
    # poll: 5
